apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: karsajobs-ui
        image: ghcr.io/rinaldyd/a433-microservices/karsajobs-ui:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
        env:
          - name: VUE_APP_BACKEND
            value: http://192.168.49.2:32436